# wrangler.toml
name = 'possineo'
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

# ===============================================================
# 1. 顶层域名控制 —— 以下禁用 Worker.dev URL
# ===============================================================
# 禁用 Production 的 *.workers.dev 域名
workers_dev = false
# 禁用 Preview / 分支部署自动生成的预览域名
preview_urls = false

# ===============================================================
# 2. 观察性配置（启用 Logs 和 Traces）
#    启用 Observability（同时开启 Workers Logs 和 Workers Traces）
# ===============================================================
[observability]
enabled = true
head_sampling_rate = 1    
# 采样率：1 表示 100% 记录所有请求日志与链路追踪（取值范围 0 到 1）

# ===============================================================
# 3. 资源绑定配置
#    以下每次CF Worker重新部署时，自动绑定KV空间。
#    本子块统一放在最下方！—— 否则报错！！！
# ===============================================================
[[kv_namespaces]]
binding = "KV"			                          #KV绑定名默认不可修改。
id = "49fcc7cb38a0474cb4f9684d7d8706dc"       #KV数据库id。
